server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9800/eureka
  instance:
    #服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    #服务续约（renew）的时间，默认30秒
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    ip-address: 127.0.0.1